# Generated by Django 6.0.4 on 2026-04-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_alter_semester_semid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.IntegerField(choices=[(1, 'Theory'), (2, 'Lab'), (3, 'Viva')], default=1),
        ),
    ]
