# Generated by Django 6.0.4 on 2026-04-11 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_alter_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='year',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
