# Generated by Django 6.0.4 on 2026-04-11 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_alter_session_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='year',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1900)]),
        ),
    ]
