# Generated by Django 6.0.4 on 2026-04-11 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_coursecodemaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='acting_chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acting_chairman', to='root.faculty'),
        ),
        migrations.CreateModel(
            name='ModeratorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('system', 'System'), ('semester', 'Semester')], max_length=10)),
                ('can_create_semester', models.BooleanField(default=False)),
                ('can_view_semester_bill', models.BooleanField(default=False)),
                ('can_view_all_bills', models.BooleanField(default=False)),
                ('can_view_session_bills', models.BooleanField(default=False)),
                ('can_approve_requests', models.BooleanField(default=False)),
                ('view_only', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_roles', to='root.faculty')),
            ],
            options={
                'unique_together': {('user', 'semester')},
            },
        ),
    ]
