# Generated by Django 6.0.4 on 2026-04-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_semester_acting_chairman_moderatorrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CourseExaminer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('first', 'First Examiner'), ('acting_first', 'Acting First Examiner'), ('external', 'External Examiner'), ('third', 'Third Examiner')], max_length=15)),
                ('paper_count', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiners', to='root.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.faculty')),
            ],
            options={
                'unique_together': {('course', 'faculty', 'role')},
            },
        ),
    ]
