# Generated by Django 6.0.4 on 2026-04-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0018_semester_is_archived_courseexaminer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_profile_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
