# Generated by Django 6.0.4 on 2026-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_acceptedcredit_faculty_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('session', 'semId')},
        ),
    ]
