# Generated by Django 6.0.4 on 2026-04-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_alter_faculty_email_alter_faculty_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
