# Generated by Django 6.0.4 on 2026-04-11 12:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_semester_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
