# Generated by Django 6.0.4 on 2026-04-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_registrationrequest_invitation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
